documentation 📝:
  - "community/**"
  - "ecosystem/**"
  - "docs/**"
dependencies 📦:
  - "package.json"
  - "pnpm-lock.yaml"
  - "yarn.lock"
enhancement ✨:
  - "functions/**"
  - "static/**"
  - "src/**"
  - "lib/**"
maintenance 📈:
  - ".github/CODEOWNERS"
  - ".github/*.md"
  - ".github/*.yml"
  - ".github/*.json"
  - ".vscode"
  - "tsconfig.json"
  - "babel.config.js"
  - "docusaurus.config.js"
  - ".all-contributorsrc"
  - "crowdin.yml"
  - "netlify.toml"
  - ".prettierrc"
  - ".prettierignore"
  - ".markdownlint.json"
  - ".deepsource.toml"
  - ".trunk/*.yaml"
  - ".trunk/*.json"
  - ".trunk/*rc"
i18n 🌐:
  - "i18n/**"
annex 🌀:
  - "ecosystem/annexes/**"
  - "i18n/**/docusaurus-plugin-content-ecosystem/**/annexes/**"
package 📦:
  - "ecosystem/packages/**"
  - "i18n/**/docusaurus-plugin-content-ecosystem/**/packages/**"
plugin ⚙️:
  - "ecosystem/plugins/**"
  - "i18n/**/docusaurus-plugin-content-ecosystem/**/plugins/**"
ci 🤖:
  - ".github/workflows/*.yml"
