project_id_env: CROWDIN_PROJECT
api_token_env: CROWDIN_TOKEN
base_url: 'https://digitalclouds.crowdin.com'
preserve_hierarchy: true
commit_message: '[skip ci]'
files:
  ### JSON translation files
  - source: '/i18n/en/**/*'
    translation: '/i18n/%two_letters_code%/**/%original_file_name%'
  ### Docs Markdown files
  - source: '/docs/**/*'
  #  ignore:
  #    - ''
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%'
  ### Community Docs Markdown files
  #- source: '/ecosystem/**/*'
  #  translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-ecosystem/current/**/%original_file_name%'
  ### Community Docs Markdown files
  - source: '/community/**/*'
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-community/current/**/%original_file_name%'
