extends:
  - stylelint-config-standard
  - stylelint-config-recommended
  - stylelint-config-recess-order
  - stylelint-config-prettier
plugins:
  - stylelint-color-format
rules:
  {
    "no-descending-specificity": true,
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": true,
    "keyframe-declaration-no-important": true,
    "color-no-invalid-hex": true,
    "color-format/format": {"format": "hsl"},
    "selector-pseudo-class-no-unknown": [true, {ignorePseudoClasses: ["global"]}],
    "value-keyword-case": ["lower", {camelCaseSvgKeywords: true}],
    "alpha-value-notation": ["percentage", {"exceptProperties": ["opacity"]}],
    "block-no-empty": null,
    "selector-class-pattern": null,
    "order/properties-alphabetical-order": null,
  }
