---
name: '🚀 Deploy'
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install
      - run: pnpm test

  upload:
    needs: [deploy]
    name: '🆙'
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    secrets:
      trunk-token: ${{ secrets.TRUNK_TOKEN }}
