---
name: "🚀 Test Build"
on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: "🚀"
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    with:
      node_version: "16"
      pnpm_arguments: "pnpm i && pnpm run build"
    secrets:
      trunk-token: ${{ secrets.TRUNK_TOKEN }}
