---
name: '🚀 Deploy'
on:
  workflow_dispatch:
  workflow_run:
    workflows: [♻️ Trunk Check]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: |
          pnpm i
          pnpm run build:en
