---
name: '🚀 Deploy'
on:
  #  push:
  #    paths-ignore: [i18n]
  #    branches: [main]
  #  pull_request:
  #    paths-ignore: [i18n]
  #    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true
      - run: pnpm run test
#      - name: '⚡'
#        uses: z-shell/.github/.github/workflows/trunk.yml@main
