---
name: "🔄 Rclone"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
#  schedule:
#    - cron: "0 07 * * 5"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@v3
      - name: "⏫ Rclone"
        uses: z-shell/.github/actions/rclone@main
        with:
          RCLONE_CONF: ${{ secrets.RCLONE_STORE }}
          RUN: sync static r2store:r2-store/public
          #RCLONE_CONF_PATH:
