---
name: "🔄 Rclone"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
#  schedule:
#    - cron: "0 07 * * 5"
  workflow_dispatch: {}

jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@v3
      - name: "⏫ Rclone"
        uses: z-shell/.github/actions/rclone@main
        env:
          RCLONE_CONF: ${{ secrets.R2_STORE }}
          RCLONE_CONF_PATH: "$HOME/.config/rclone"
        with:
          # Run required arguments with rclone (required)
          RUN: sync static r2store:r2-store/public
