---
name: '⭕ Trunk'
on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

jobs:
  check:
    name: '⚡'
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    with:
      runs-on: 'ubuntu-latest'
      node_version: '16'
      pnpm_arguments: 'pnpm i && pnpm run build:en'
